function loopOptSwapYieldYeastAerobic

    cleaner = onCleanup(@() cleanup);
    global run status
    status = 'starting';
    run = 'optSwapYieldYeast';
    logFile = sprintf('optSwapYieldYeast_aerobic_%s.tsv', ...
                      datestr(now, 'yy-mm-dd_HH_MM_SS'));
    global fileId
    fileId = fopen(logFile, 'a');
    fprintf(fileId, ['target\taerobic\tsubstrate\tnum swaps\tthko\' ...
                     'tf_k\tmax yield\tswaps\ttime (s)\n']);
    fclose(fileId);

    % glc, D-xyl, gylc, L-arab
    substrates = {'EX_glc(e)', 'EX_xyl-D(e)'};
    aer = {'aerobic'};
    swaps = [0, 1, 2];
    for i=1:length(substrates)
        for j=1:length(aer)
            for k=1:length(swaps)
                opt.thko = 'nothko';
                opt.substrate = substrates{i};
                opt.aerobicString = aer{j};
                opt.swapNum = swaps(k);
                opt.logFile = logFile;
                opt.modelname = 'iMM904';
                opt.targetRxns = yeastTargets(opt.modelname);
                opt.dhRxns = yeastDhPool();
                runOptSwapYield(opt);
            end
        end
    end
end

function pool = yeastDhPool()
    pool = {'GAPD', ...
            'NADH2-u6cm', ...
            'ICDHy', ...
            'GLUDyi', ...
            'PGCD', ...
            'ALDD2y', ...
            'GND', ...
            'G6PDH2', ...
            'ASADi', ...
            'HSDxi', ...
            'IPMD', ...
            'AASAD2', ...
            'SACCD1', ...
            'SACCD2', ...
            'SHK3D', ...
            'G3PD1ir', ...
            'XYLR', ...
            'XYLTD_D', ...
            'ALCD2x', ...
            'GLUSx', ...
            'MDH', ...
            'GLYCDy'};
end

function targets = yeastTargets(modelName)
    model = loadModelNamed(modelName);
    targets = model.rxns(findExcRxns(model));
end